import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillMail, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { useState } from "react";
import Image from "next/image";
import personalPic from "../public/personalPic.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const personalProjectsObj = [
    {
      title: "Pawster",
      liveSiteLink: "https://pawster-frontend.netlify.app",
      githubLink: "https://github.com/ametzamaldonado/Pawster-capstone-project",
      techLangUsed: "React | Javascript | CSS | HTML | Express",
      description: "< Project description here! >",
    },
    {
      title: "Youtube Clone",
      liveSiteLink: "https://youtube-team-4.netlify.app/",
      githubLink: "https://github.com/ametzamaldonado/react-youtube-app",
      techLangUsed: "React | Javascript | CSS | HTML | Express",
      description: "< Project description here! >",
    },
    {
      title: "Budgeting App",
      liveSiteLink: "https://budgeting-app-101.netlify.app/",
      githubLink: "https://github.com/ametzamaldonado/new-budget-app",
      techLangUsed: "React | Javascript | CSS | HTML | Express",
      description: "< Project description here! >",
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ametza Maldonado's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">ADM</h1>
            <ul className="flex items-center">
              <li>
                {darkMode ? (
                  <BsFillSunFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-600 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://docs.google.com/document/d/1KQCjmGtU2QJ-hmPTbpXr9mGy_uOYyxjM/export?format=pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Ametzayin Maldonado
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              FullStack Web Developer
            </h3>

            <div className="mx-auto bg-gradient-to-b from-slate-400 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={personalPic} layout="fill" objectFit="cover" />
            </div>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Welcome to my personal portfolio website!
              <br />
              <br />
              As a recent graduate of the Pursuit Fellowship, I have gained a
              strong foundation in various technologies such as JavaScript,
              HTML, CSS, Node, Express, React/Redux, and PostgreSQL; as well as
              gained experience working with APIs. In addition, I have learned
              about data structures, algorithms, and the Agile software
              development method through sprints. Throughout my time at the
              Pursuit Fellowship, I have had the opportunity to build a variety
              of projects that have allowed me to hone my skills and showcase my
              abilities. On this website, you will find an overview of my
              completed projects as well as my professional experience. Thank
              you for visiting my portfolio website. I hope you find it
              informative and that it provides a clear sense of my capabilities
              as a software developer.
            </p>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.linkedin.com/in/ametzayin-maldonado-3528b6124/"
                target="_blank"
              >
                <AiFillLinkedin className="dark:text-white" />
              </a>
              <a href="https://github.com/ametzamaldonado" target="_blank">
                <AiFillGithub className="dark:text-white" />
              </a>
              <a href="mailto:ametza.maldonado@gmail.com?subject=Personal Profolio Comment/Question">
                <AiFillMail className="dark:text-white" />
              </a>
            </div>
          </div>
        </section>

        <section className="py-7 mx-auto">
          <div>
            <h2 className="text-4xl py-2 text-teal-600 text-center font-bold md:text-4xl  dark:text-white">
              My Projects
            </h2>
          </div>

          <div className="lg:flex gap-10">

            {personalProjectsObj.map((item) => (
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <h3 className="text-2xl font-medium pt-8 pb-2 ">
                  {item.title}
                </h3>
                <div className="flex justify-around dark:text-white">
                  <a
                    className="bg-gradient-to-r from-gray-600 text- to-gray-400 text-white px-4 py-2 rounded-lg mr-1"
                    href={item.liveSiteLink}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Live Site
                  </a>

                  <a
                    className="bg-gradient-to-r from-gray-600 text- to-gray-400 text-white px-4 py-2 rounded-lg ml-1"
                    href={item.githubLink}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Github
                  </a>
                </div>
                <h4 className="text-xl pt-3 text-teal-600 font-semibold">
                  Tech Stack:
                </h4>
                <p className="text-gray-800 py-1 text-md font-semibold">
                  {item.techLangUsed}{" "}
                </p>

                <p className="px-10">{item.description}</p>
              </div>
            ))}

          </div>
        </section>

        {/* Section for photos displaying projects worked on! */}
        
        {/* <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section> */}

        <footer className="py-10 mt-12">
          <div className="flex justify-between">
            <h1 className="text-xl font-burtons  dark:text-white">
              developedbyADM
            </h1>
            <div className="text-lg dark:text-white">
              <p>Built using Next.js && Tailwind</p>
              <p>Copyright © ADM</p>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
3;
